# vprm_shapeshifter.R
# Conversion tool that morphs VPRM input files generated by VPRM preprocessor on Panorama (Christoph Gerbig)
# into final vprm_input_dXX_[date] files read by WRF-CHEM
# M. Galkowski, MPI-BGC Jena, 2018


# For detailed description of the variables, see function source file (f_vprm_shapeshifter.R)

# This script runs on Mistral, DKRZ.
source("/work/mj0143/b301033/Projects/WRF_Tools/vprm_shapeshifter/f_vprm_shapeshifter.R")


# Code for example run on Mistral (DKRZ) for CoMet 2018 mission:
f_vprm_shapeshifter( vprm_input_dir    = "/work/mj0143/b301033/Data/CoMet_input/Emissions/VPRM_input/MODIS_indices/JFS.Reanalysis_v1",
                           output_dir        = "/work/mj0143/b301033/Data/CoMet_input/Emissions/VPRM_input/WRF_input",
                           requested.domains = "d03", #c("d01", "d02", "d03"),
                           current.year      = 2018,
                           #previous.year     = 2017, NOT AVAILABLE FOR D03 expanded to Belchatow
                           add.kaplan.model.input = T,
                           kaplan_input_dir  = "/work/mj0143/b301033/Data/CoMet_input/Emissions/VPRM_input/Kaplan_wetlands/vprm_shapeshifter_input")


# DEVELOPMENT / TESTS ##########################################################################################3
# Code for example run on Mistral (DKRZ) for development / testing:
#f_preprocess.VPRM.for.WRF( input_dir      = "/work/mj0143/b301033/Data/CoMet_input/Emissions/VPRM_input/yearly",
#                          output_dir     = "/work/mj0143/b301033/Projects/WRF_Tools/vprm_shapeshifter/results",
                        #  requested.domains = "d01",
                         # current.year   = 2018,
                         # add.kaplan.model.input     = F,
                         # load.precalculated.indices = F )
