# vprm_shapeshifter.R
# Conversion tool that morphs VPRM input files generated by VPRM preprocessor on Panorama (Christoph Gerbig)
# into final vprm_input_dXX_[date] files read by WRF-CHEM
# M. Galkowski, MPI-BGC Jena, 2018


# Operational folder for preparing WRF-input for CoMet runs.
# Main function enables running for a single domain, which is selected
# in the function call below. For detailed description, see function source
# file.

# This script runs on Mistral, DKRZ.
source("/work/mj0143/b301033/Projects/WRF_Tools/vprm_shapeshifter/f_preprocess.VPRM.for.WRF.R")


# Santiago Botia: ATTO/Amazon domain
f_preprocess.VPRM.for.WRF( input_dir         = "/work/mj0143/b301034/data_input/vprm_fields/RAW_VPRM_Gerbig/ATTO_27_9_3_1kmV3",
                           output_dir        = "/work/mj0143/b301034/data_input/vprm_fields/WRF_ready_files/ATTO_27_9_3_1kmV3",
                           requested.domains = "d04",
                           current.year      = 2014,
                           previous.year     = 2014,
                           add.kaplan.model.input     = T )
